name: Publish
on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/brixel/haspman-main
          tags: type=semver,pattern={{version}},value=${{ steps.gitversion.outputs.semVer }}
      - name: Replace placeholder tokens\
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["Infrastructure/helm-charts/haspman/Chart.yaml"]'
        env:
          GITVERSION_SEMVER: ${{ steps.gitversion.outputs.semVer }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: HaSpMan.Web.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - name: Configure Git
        run: |
          git config user.name "Helm chart releaser"
          git config user.email "helm-chart-releaser@users.noreply.github.com"
      - name: Publish helm chart
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: Infrastructure/helm-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
